stages:
  dataset_download:
    cmd:  python src/dataset_downloading.py
    params:
    - dataset_download.path
    - dataset_download.split
    outs:
    - data/dataset/input
  captioning:
    cmd: pdm run src/captioning.py
    params:
      - captioning.provider
      - captioning.model
      - captioning.prompt_template
    outs:
      - data/dataset/output