stages:
  data_collection:
    cmd:  pdm run src/data_collection.py
    params:
    - data_collection.path
    - data_collection.split
    outs:
    - data/dataset/input
    deps:
    - src/data_collection.py
  data_preprocessing:
    cmd: pdm run src/data_preprocessing.py
    # params:
    outs:
    - data/dataset/preprocessed
    deps:
    - src/data_preprocessing.py
    # - data/dataset/input
  caption_generation:
    cmd: pdm run src/caption_generation.py
    params:
      - caption_generation.prompt_template
      - caption_generation.provider
      - caption_generation.model
    outs:
      - data/dataset/output
    deps:
      - src/caption_generation.py
      # - data/dataset/preprocessed
  caption_evaluation:
    cmd: python src/caption_evaluation.py
    params:
      - caption_evaluation.prompt_template
      - caption_evaluation.provider
      - caption_evaluation.model
    outs:
      - data/dataset/evaluated
    deps:
      - src/caption_evaluation.py
      # - data/dataset/output
    metrics:
      - data/eval/metrics.json
