
data_collection:
  path: kraina/text2tile
  split: train[:10]

# data_preprocessing:
  

# caption_generation:
#   prompt_template: complex
#   provider: openai
#   model: gpt-4o-mini

# caption_evaluation:
#   prompt_template: complex
#   provider: openai
#   model: gpt-4o-mini

# caption_generation:
#   prompt_template: complex
#   provider: vertexai
#   model: gemini-1.5-pro-002

# caption_evaluation:
#   prompt_template: complex
#   provider: vertexai
#   model: gemini-1.5-flash-002


caption_generation:
  prompt_template: complex
  provider: ollama
  model: llama3.2-vision
  dataset_name: llama3.2-vision-captioned

caption_evaluation:
  prompt_template: complex
  provider: vertexai
  model: gemini-1.5-pro-002


