
downloading:
  path: kraina/text2tile
  split: train[:20]

preprocessing:
  prompt_template: complex

captioning:
  provider: ollama
  model: llava-llama3

evaluation:
  prompt_template: basic
  provider: ollama
  model: llava-llama3