from abc import ABC, abstractmethod


# Abstract base class defining the interface for captioning
class CaptioningBase(ABC):
    @abstractmethod
    def generate_caption(self, model_name: str, img_str: str, prompt: str) -> str:
        """
        Generate a caption for the given image.

        Parameters:
            model_name (str): name of the model
            img_str (str): Base64 encoded image string.
            prompt (str): prompt for generation

        Returns:
            str: Caption generated by the LLM provider.
        """
        pass
