from abc import ABC, abstractmethod


# Abstract base class defining the interface for captioning
class BaseCaptioning(ABC):
    @abstractmethod
    def generate_caption(
        self,
        model: str,
        prompt: str,
        image: str,
    ) -> str:
        """
        Generate a caption for the given image.

        Parameters:
            model_name (str): name of the model
            img_str (str): Base64 encoded image string.
            prompt (str): prompt for generation

        Returns:
            str: Caption generated by the LLM provider.
        """

    @abstractmethod
    def evaluate_caption(self, model: str, prompt: str) -> str:
        """
        Evaluate the caption generated by the model.

        Parameters:
            model_name (str): name of the model
            prompt (str): prompt for evaluation

        Returns:
            str: Evaluation score of the caption.
        """
